# Conclusion

The MBAn student body and the business community as a whole stand on the precipice of a new age of commerce. The benefits provided by AI have allowed firms across numerous industries to improve on their processes both internal and external. According to a global survey by McKinsey, a significant portion of executives from companies that have adopted AI report an increase in revenue in the business areas it influenced. Specifically, 63% of respondents claimed a revenue boost from AI integration. AI's potential to optimize company-wide operations also translates into significant cost savings. McKinsey's report highlights that 44% of the executives observed a reduction in costs due to the adoption of AI in their business operations (McKinsey Company, 2019). Business students should consider AI’s current impact and its future so they may thrive as tomorrow’s leaders. Yet, this is a task easier said than done; with so many industries applying AI in so many ways, it is difficult to understand such a revolutionary technology via a holistic analysis. This report has mainly focused on front-stage elements in a few key industries that individuals are likely to interact with as workers and consumers. It is also important to acknowledge that students are not the only ones struggling to understand the impact of AI. There is an immense need for regulation, and it falls on business leaders informed on the issue to guide governments toward effective policies. This is especially important considering the conflict between managers, workers, and technology that is ongoing. MBAn students therefore face a dual responsibility. The first is to research AI applications to build more efficient businesses. The second is to develop systems of control for AI so that it does not have an adverse impact on consumers or businesses. The journey of integrating AI into the business landscape, while promising transformative benefits, has many challenges. Understanding and addressing these obstacles is necessary for any future executive looking to harness AI's full potential in their organization. 
